"""
    GEO_Test API

    geo_test API as RESTFul service to offer basic geo services  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: luipir@gmail.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="GEO_Test API",
    author="OpenAPI Generator community",
    author_email="luipir@gmail.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "GEO_Test API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Creative Common CC-BY-SA",
    long_description="""\
    geo_test API as RESTFul service to offer basic geo services  # noqa: E501
    """
)
