# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Props(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, string_value=None, integer_value=None):  # noqa: E501
        """Props - a model defined in OpenAPI

        :param string_value: The string_value of this Props.  # noqa: E501
        :type string_value: str
        :param integer_value: The integer_value of this Props.  # noqa: E501
        :type integer_value: float
        """
        self.openapi_types = {
            'string_value': str,
            'integer_value': float
        }

        self.attribute_map = {
            'string_value': 'string_value',
            'integer_value': 'integer_value'
        }

        self._string_value = string_value
        self._integer_value = integer_value

    @classmethod
    def from_dict(cls, dikt) -> 'Props':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Props of this Props.  # noqa: E501
        :rtype: Props
        """
        return util.deserialize_model(dikt, cls)

    @property
    def string_value(self):
        """Gets the string_value of this Props.


        :return: The string_value of this Props.
        :rtype: str
        """
        return self._string_value

    @string_value.setter
    def string_value(self, string_value):
        """Sets the string_value of this Props.


        :param string_value: The string_value of this Props.
        :type string_value: str
        """

        self._string_value = string_value

    @property
    def integer_value(self):
        """Gets the integer_value of this Props.


        :return: The integer_value of this Props.
        :rtype: float
        """
        return self._integer_value

    @integer_value.setter
    def integer_value(self, integer_value):
        """Sets the integer_value of this Props.


        :param integer_value: The integer_value of this Props.
        :type integer_value: float
        """

        self._integer_value = integer_value
