"""
    GEO_Test API

    geo_test API as RESTFul service to offer basic geo services  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: luipir@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.point3_d_dict import Point3DDict


class TestPoint3DDict(unittest.TestCase):
    """Point3DDict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoint3DDict(self):
        """Test Point3DDict"""

        # constructor with all params
        args = {
            'lat': 1.0,
            'lon': 2.0,
            'altitude': 3.0
        }
        model = Point3DDict(**args)
        for key in args:
            self.assertTrue( hasattr(model, key) )
            self.assertEqual( getattr(model, key), args[key])

        # constructor with only lat and lon
        args = {
            'lat': 1.0,
            'lon': 2.0
        }
        model = Point3DDict(**args)
        for key in args:
            self.assertTrue( hasattr(model, key) )
            self.assertEqual( getattr(model, key), args[key])
        self.assertFalse( hasattr(model, 'altitude') )

        # accept only float
        args = {
            'lat': 1,
            'lon': 2.0
        }
        with self.assertRaises(openapi_client.exceptions.ApiTypeError) as ex:
            Point3DDict(**args)

        # accept only float
        args = {
            'lat': '1',
            'lon': 2.0
        }
        with self.assertRaises(openapi_client.exceptions.ApiTypeError) as ex:
            Point3DDict(**args)

if __name__ == '__main__':
    unittest.main()
