"""
    GEO_Test API

    geo_test API as RESTFul service to offer basic geo services  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: luipir@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.props import Props


class TestProps(unittest.TestCase):
    """Props unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProps(self):
        """Test Props"""
        args = {
            'key1': 'value1',
            'key2': 'value2'
        }
        model = Props(**args)
        
        # check model has set attribute as from inpur params
        for key in args:
            self.assertTrue( hasattr(model, key) )
            self.assertEqual( getattr(model, key), args[key])
        
        # check that accept only strings
        args = {
            'key1': 'value1',
            'key2': 11111
        }
        with self.assertRaises(openapi_client.exceptions.ApiTypeError) as ex:
            Props(**args)

        # check allo empty props no rise exception
        args={}
        Props(**args)


if __name__ == '__main__':
    unittest.main()
