"""
    GEO_Test API

    geo_test API as RESTFul service to offer basic geo services  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: luipir@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.search_api import SearchApi  # noqa: E501

####################################################################3
####################################################################3
####################################################################3
####################################################################3
#
#                         README
#
# I hadn't time to complete this test btw see integration tests
# that would cover most of this call
####################################################################3
####################################################################3
####################################################################3
####################################################################3
####################################################################3

class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_area_by_date(self):
        """Test case for get_area_by_date

        Retrieve a Area with a specified data.  # noqa: E501
        """
        pass

    def test_get_area_by_name(self):
        """Test case for get_area_by_name

        Retrieve a Area resource by unique name.  # noqa: E501
        """
        pass

    def test_get_area_by_properties(self):
        """Test case for get_area_by_properties

        Retrieve a Area with a specified data set of properties.  # noqa: E501
        """
        pass

    def test_get_intersect(self):
        """Test case for get_intersect

        Retrieve a Area inteersecting posted polygon.  # noqa: E501
        """
        pass

    def test_get_intersection(self):
        """Test case for get_intersection

        Retrieve Area inside input polygon.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
