"""
    GEO_Test API

    geo_test API as RESTFul service to offer basic geo services  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: luipir@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.modification_api import ModificationApi  # noqa: E501


####################################################################3
####################################################################3
####################################################################3
####################################################################3
#
#                         README
#
# I hadn't time to complete this test btw see integration tests
# that would cover most of this call
####################################################################3
####################################################################3
####################################################################3
####################################################################3
####################################################################3

class TestModificationApi(unittest.TestCase):
    """ModificationApi unit test stubs"""

    def setUp(self):
        self.api = ModificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_area(self):
        """Test case for add_area

        Add new/modify Area resource  # noqa: E501
        """
        pass

    def test_delete_are_by_name(self):
        """Test case for delete_are_by_name

        Delete a Area resource by name.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
